apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customers-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoices-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipments-data
  namespace: ecommerce
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi